/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RECORD_X_H_RPCGEN
#define _RECORD_X_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct attr_x {
	char *name;
	char *value;
};
typedef struct attr_x attr_x;

struct attrlist_x {
	attr_x attr;
	struct attrlist_x *next;
};
typedef struct attrlist_x attrlist_x;

struct Record_x {
	char *name;
	attrlist_x *attributes;
};
typedef struct Record_x Record_x;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_attr_x (XDR *, attr_x*);
extern  bool_t xdr_attrlist_x (XDR *, attrlist_x*);
extern  bool_t xdr_Record_x (XDR *, Record_x*);

#else /* K&R C */
extern bool_t xdr_attr_x ();
extern bool_t xdr_attrlist_x ();
extern bool_t xdr_Record_x ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RECORD_X_H_RPCGEN */
